import '@/styles/globals.scss'
import { Inter } from 'next/font/google'
import { LocaleProvider } from '@/context/LocaleContext';
import { MenuControlProvider } from '@/context/MenuControlContext';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
        <body>
          <MenuControlProvider>
            <LocaleProvider>
              {children}
            </LocaleProvider>
          </MenuControlProvider>
        </body>
      </html>
  )
}
