import "@/styles/globals.scss";
import { Inter } from "next/font/google";
import {
	LocaleProvider,
	MenuControlProvider,
	TagsControlProvider,
	CalendarProvider,
} from "@/context";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<MenuControlProvider>
					<LocaleProvider>
						<CalendarProvider>
							<TagsControlProvider>{children}</TagsControlProvider>
						</CalendarProvider>
					</LocaleProvider>
				</MenuControlProvider>
			</body>
		</html>
	);
}
